version: '3'

services:
  mssql-server:
    build:
      context: ./mssql-server
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: Un!q@to2023
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - mssql-data:/var/opt/mssql
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mssql-server

volumes:
  mssql-data:
    driver: local
